// sber-test-vue3/src/components/trees/list/TreesList.vue
<template>
<div :class="componentClass">
    <div class="search">
        <SearchInputText description="Введите значение для поиска дерева или свойства дерева" :disabled="dataIsLoading" :showDescription="true" @onEnter="onSearchEnter"/>
    </div>
    <div class="content" v-if="hasList">
        <div class="content__header">
            <typography variant="h2-title">
                {{ getTitle }}
            </typography>
        </div>
        <div class="content__list">
            <TreeComponent v-for="item in treeList.items" :key="JSON.stringify(item)" :item="item"/>
        </div>
    </div>
    <div class="empty-message" v-else>
        <typography variant="h3-title">
            Выберите категорию      
        </typography>
    </div>
</div>
</template>

<script lang="ts">
import { Options, Vue } from 'vue-class-component'
import * as utils from './../../../services/utils'
import {TreeList} from './../../../services/types'
import { StoreActionTypes } from './../../../store/types'
import SearchInputText from './../../input/SearchInputText.vue' 
import TreeComponent from './../item/Tree.vue'

@Options({
    components: {
        SearchInputText,
        TreeComponent
    }
})
export default class TreesList extends Vue {
    private componentClass = "TreesList"

    get hasList(): boolean {
        return !utils.isEmptyObj(this.treeList)
    }

    get treeList(): TreeList {
        return this.$store.getters.getTreesList
    }

    get getTitle(): string {
        return this.treeList.title
    }

    get dataIsLoading(): boolean {
        return this.$store.getters.isTreesDataLoading
    }

    async onSearchEnter(text: string){
        await this.$store.dispatch(StoreActionTypes.SEARCH_TREE_LIST, text)
    }
}
</script>

<style lang="scss" scoped>
.TreesList {
    padding: 20px 0 0 20px;
}

.search {
    margin-bottom: 20px;
}
</style>

// sber-test-react/src/components/trees/list/TreesListComponent.tsx
import * as React from "react"

import { TypographyComponent } from "../../typography/Typography"
import * as utils from './../../../services/utils'
import {SearchComponent} from "../../search/SearchComponent"

import { TreeComponent } from "../item/tree/TreeComponent"
import * as I from './ITreesList'

export const TreesListComponent : React.FC<I.Props> = props =>  {
    const componentClass = "TreesListComponent"

    const {list, items} = props

    const getHeader = () => {
        return (
            <TypographyComponent variant="h2-title">
                {list.title}
            </TypographyComponent>
        )
    }

    const getList = () => items.map(item => <TreeComponent item={item} key={JSON.stringify(item)}/>)

    const getContent = () => {
        if (!utils.isEmptyObj(list)) {
            return (
                <React.Fragment>
                    <div className={`${componentClass}__search`}>
                        <SearchComponent dataIsLoading={props.dataIsLoading} search={props.searchTreeList} description="Введите значение для поиска дерева или свойства дерева"/>
                    </div>                    
                    <div className={`${componentClass}__header`}>
                        {getHeader()}
                    </div>
                    <div className={`${componentClass}__list`}>
                        {getList()}
                    </div>
                </React.Fragment>
            )
        }
        else {
            return (
                <div className={`${componentClass}__empty`}>
                    <TypographyComponent variant="h3-title">
                        Выберите категорию
                    </TypographyComponent>
                </div>                
            )
        }
    }

    return (
        <div className={componentClass}>
            {getContent()}
        </div>        
    );
}
